#### Chapter 3: Built-in data structures, functions and files

In [1]:
# an easy way of creating a tuple:

tup_1 = 4,5,67,98
tup_1

(4, 5, 67, 98)

In [2]:
# while creating a tuple inside a tuple, use ():

tup_2 = ((tup_1),456,"Rajarshi","Shivani", 12)
tup_2

((4, 5, 67, 98), 456, 'Rajarshi', 'Shivani', 12)

In [4]:
tuple([4,5,672,"Rajarshi"])

(4, 5, 672, 'Rajarshi')

In [7]:
tuple("Rajarshi")

('R', 'a', 'j', 'a', 'r', 's', 'h', 'i')

In [13]:
tup_3 = tuple(['Rajarshi', [4,5,789], 'Commodities', True])
tup_3

('Rajarshi', [4, 5, 789], 'Commodities', True)

In [14]:
tup_3 = False

In [16]:
tup_3 = True

In [21]:
# in the above tuple_3, the object at index 1 is a list, which can be modified in place:

tup_3

True

In [22]:
tup_3 = tuple(['Rajarshi', [4,5,789], 'Commodities', True])
tup_3

('Rajarshi', [4, 5, 789], 'Commodities', True)

In [25]:
tup_3[1].append(201)
tup_3 #the no 201 is appended at the end of the list comprising [4,5,789]

('Rajarshi', [4, 5, 789, 201], 'Commodities', True)

In [26]:
tup_4 = ("Rajarshi", "Shivani", "Phuchka")*2
tup_4

('Rajarshi', 'Shivani', 'Phuchka', 'Rajarshi', 'Shivani', 'Phuchka')

In [29]:
# to pluck a few elements from a tuple:

tup_5 = (2,4,6,8,43,879,112,70)
a,b,*rest = tup_5
a,b

(2, 4)

In [31]:
rest

[6, 8, 43, 879, 112, 70]

In [36]:
tup_4 = (1,2,34,567)
a,b,c,d = tup_4
a,b,*rest = tup_4
rest

[34, 567]

In [39]:
# diff between append and insert
list_1 = [23,345,4567,21,"Rajarshi"]
list_1


[23, 345, 4567, 21, 'Rajarshi']

##### usage convention: Tuple ( ) and List [ ]

In [40]:
list_1.append("Phuchka")
list_1

[23, 345, 4567, 21, 'Rajarshi', 'Phuchka']

In [42]:
list_1.insert(2,"Shivani")
list_1

[23, 345, 'Shivani', 23, 4567, 21, 'Rajarshi', 'Phuchka']

In [43]:
# to check is a given value is contained in a list:
'Phuchka' in list_1

True

In [47]:
# the sort method can be used to arrange the values in a list in ascending order:

list_2 = [2,89,901,45,65,8.98]
list_2.sort()
list_2

[2, 8.98, 45, 65, 89, 901]

In [53]:
list_3 = ['Jeeves','Phuchka', 'Rajarshi', 'Shivani']
list_3.sort(key=len)
list_3

['Jeeves', 'Phuchka', 'Shivani', 'Rajarshi']

In [54]:
# slicing:

list_3 = ['Jeeves','Phuchka', 'Rajarshi', 'Shivani']
list_3[1:3]

['Phuchka', 'Rajarshi']

In [55]:
list_3[:4]

['Jeeves', 'Phuchka', 'Rajarshi', 'Shivani']

In [56]:
# dictionary

dict_1 = {'name':'Rajarshi', 'age':35, 'loc':'london', 'misc': [1,2,34,56]}
dict_1

{'name': 'Rajarshi', 'age': 35, 'loc': 'london', 'misc': [1, 2, 34, 56]}

In [60]:
dict_1['occ'] = 'consultant'
dict_1

{'name': 'Rajarshi',
 'age': 35,
 'loc': 'london',
 'misc': [1, 2, 34, 56],
 'occ': 'consultant'}

In [61]:
dict_1['age']

35

In [62]:
dict_1[30] = 'months'
dict_1

{'name': 'Rajarshi',
 'age': 35,
 'loc': 'london',
 'misc': [1, 2, 34, 56],
 'occ': 'consultant',
 30: 'months'}

In [64]:
dict_1[30]

'months'

In [65]:
dict_1

{'name': 'Rajarshi',
 'age': 35,
 'loc': 'london',
 'misc': [1, 2, 34, 56],
 'occ': 'consultant',
 30: 'months'}

In [69]:
ret = dict_1.pop('age') # use ret not return; return is a function in Python
ret

35

In [70]:
dict_1

{'name': 'Rajarshi',
 'loc': 'london',
 'misc': [1, 2, 34, 56],
 'occ': 'consultant',
 30: 'months'}

In [71]:
# to display keys and values in a dict:

list(dict_1.keys())

['name', 'loc', 'misc', 'occ', 30]

In [72]:
list(dict_1.values())

['Rajarshi', 'london', [1, 2, 34, 56], 'consultant', 'months']

In [73]:
dict_1.pop('misc')
dict_1

{'name': 'Rajarshi', 'loc': 'london', 'occ': 'consultant', 30: 'months'}

In [77]:
# using sets for mathematical operations:

set_1 = {1,2,3,4,5}
set_2 = {3,4,34,45,56,7,89}
set_1.union(set_2)

{1, 2, 3, 4, 5, 7, 34, 45, 56, 89}

In [78]:
set_1.intersection(set_2)

{3, 4}

In [79]:
# difference between union method and symmetric_difference method:

set_1.union(set_2) # this returns only unique values

{1, 2, 3, 4, 5, 7, 34, 45, 56, 89}

In [80]:
set_1.symmetric_difference(set_2) # returns all unique values except those that are present in both sets

{1, 2, 5, 7, 34, 45, 56, 89}

In [82]:
# using functions:

def function_1(x,y,z=1.5):
    if z > 1:
        return z*(x+y)
    else:
        return z/(x+y)

In [93]:
# using functions as objects:

states = [' Alabama', 'Georgia!', 'Georgia', 'georgia', 'Florida', 'souTH carolina##', 'West Virginia??']

import re

def clean_strings(states):
    result = []
    for value in states:
        value = value.strip()
        value = value.title()
        value = re.sub('[!#?]', '', value)
        result.append(value)        
    return result

In [96]:
clean_strings(states)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South Carolina',
 'West Virginia']

#### Chapter 4: NumPy

In [1]:
import numpy as np

In [3]:
# generate some random arrays:

array_1 = np.random.randn(2,3)
array_1

array([[-0.23486253, -2.01993909,  0.85184208],
       [-0.94687728, -0.24035297, -0.06242667]])

In [4]:
array_1*2

array([[-0.46972507, -4.03987817,  1.70368417],
       [-1.89375455, -0.48070594, -0.12485334]])

In [5]:
array_1+array_1

array([[-0.46972507, -4.03987817,  1.70368417],
       [-1.89375455, -0.48070594, -0.12485334]])

In [8]:
# to find the shape and type of an array:

array_1.shape # shape of the array in terms of rows and columns
array_1.dtype # data type - integer or float

dtype('float64')

In [10]:
# creating arrays:

data_1 = [6,7.5,78,32,44]
array_1 = np.array(data_1)
array_1

array([ 6. ,  7.5, 78. , 32. , 44. ])

In [11]:
data_2 = [[1,2,3,4],[5,6,7,78]]
array_2 = np.array(data_2)
array_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7, 78]])

In [12]:
array_2.dtype

dtype('int64')

In [13]:
array_2.shape

(2, 4)

In [19]:
# other methods used with arrays:

np.zeros(10)
np.empty((2,3,2))
np.arange(15) #this is the array-range (a-range) version for arrays

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### Chapter 5: Getting started with Pandas

In [20]:
# whenever we wil work with pandas, we will import the following libraries:

import pandas as pd

In [21]:
from pandas import Series, DataFrame

In [24]:
obj = pd.Series([23,46,1,98,0.25])
obj.dtype

dtype('float64')

In [25]:
obj # the string representation below shows the index along with the values

0    23.00
1    46.00
2     1.00
3    98.00
4     0.25
dtype: float64

In [29]:
obj.values[3:]

array([98.  ,  0.25])

In [32]:
# creating an index with labels assigned to the values:

obj_2 = pd.Series([2,3,4,98], index=['a','b','c','d'])
obj_2

a     2
b     3
c     4
d    98
dtype: int64

In [33]:
obj_2['c']

4

In [34]:
#if we want to convert a Dict to a Series:

dict = {'Ohio':35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
dict

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [37]:
# the above output is that of a dictionary; now we will convert this into a pandas Series:

series = pd.Series(dict)
series

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [38]:
# creating a DataFrame:

data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year':[2000,2001,2002,2001,2002,2003],
        'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame_1 = pd.DataFrame(data)
frame_1

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [43]:
# display the top 5 entries:

frame_1[0:5] # this is the same as using frame_1.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [45]:
# to change the sequence of columns:

pd.DataFrame(frame_1,columns = ['year', 'pop', 'state'])

year  pop   state
0  2000  1.5    Ohio
1  2001  1.7    Ohio
2  2002  3.6    Ohio
3  2001  2.4  Nevada
4  2002  2.9  Nevada
5  2003  3.2  Nevada

In [50]:
frame_1.year
frame_1.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [59]:
frame_1.loc[3]

state    Nevada
year       2001
pop         2.4
Name: 3, dtype: object

In [60]:
frame_1['debt']=16.5 # adding a new column called debt and assigning it a scalar value
frame_1

state  year  pop  debt
0    Ohio  2000  1.5  16.5
1    Ohio  2001  1.7  16.5
2    Ohio  2002  3.6  16.5
3  Nevada  2001  2.4  16.5
4  Nevada  2002  2.9  16.5
5  Nevada  2003  3.2  16.5